config:
	name: Project
	galaxy: ./configs/galaxy.yml
	solarsystem: ./configs/solar.yml
	universe: ./configs/universe.yml
	planet: ./configs/planet.yml
	moon: ./configs/moon.yml
	planet_factory: ./configs/planet_factory.yml
	moon_factory: ./configs/moon_factory.yml
	
	
	